import idaapi
import ida_funcs
import ida_bytes
import ida_name
import ida_dbg
import ida_kernwin
import sys

# --------------------------
# 配置：符号文件路径（请修改为你的 system.map 路径）
# --------------------------
SYMBOL_FILE = r"system-map-for-bohcs.map"

# --------------------------
# 载入符号文件
# --------------------------
def parse_symbol_line(line):
    line = line.strip()
    if not line or line.startswith("#"):
        return None
    parts = line.split()
    if len(parts) < 2:
        return None
    try:
        addr = int(parts[0], 16)
        name = parts[1]
        return addr, name
    except Exception:
        return None

def load_symbols(path):
    sym = {}
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for ln in f:
                p = parse_symbol_line(ln)
                if p:
                    sym[p[0]] = p[1]
    except Exception as e:
        print(f"[sym] cannot open: {path} ({e})")
        return sym
    print(f"[sym] loaded {len(sym)} symbols")
    return sym

def install_symbol(ea, name):
    try:
        ida_name.set_name(ea, name, ida_name.SN_CHECK)
    except Exception:
        pass
    try:
        if not ida_funcs.get_func(ea):
            # add_func 有时会失败（比如地址不在段中），忽略异常
            ida_funcs.add_func(ea)
    except Exception:
        pass

def install_all_symbols(sym):
    for ea, name in sym.items():
        install_symbol(ea, name)
    print("[sym] all symbols applied")

# ============================================================
# 获取函数名与偏移
# 返回 (name, off) 或 (None, None)
# ============================================================
def get_func_name_and_off(ea):
    """
    尝试按优先级返回 (name, offset):
      1) 如果 ea 在函数内部：返回函数名和从函数起点的偏移
      2) 否则如果该地址有名称：返回该名称和偏移0（视为符号基址）
      3) 否则返回 (None, None)
    """
    if ea is None or ea == idaapi.BADADDR:
        return None, None

    f = ida_funcs.get_func(ea)
    if f:
        base = f.start_ea
        name = ida_name.get_name(base)
        if not name:
            # 如果函数没有名称，尝试取函数起点的 autogenerated 名称
            name = ida_name.get_name(base)
        off = ea - base
        return name, off

    # 非函数区域，尝试取该地址的名称
    name = ida_name.get_name(ea)
    if name:
        return name, 0

    return None, None

# ============================================================
# 构造前缀文本（被 func_line_rendering 调用）
# ============================================================
def make_prefix(ea):
    """
    生成 prefix 文本：
      - 指令行： func+0xOFF
      - 数据/变量/非指令：直接返回符号名（若有）
      - 无符号：返回空字符串（不修改前缀）
    """
    name, off = get_func_name_and_off(ea)
    if not name:
        return ""

    # 判定该行是否为代码（尽量可靠地判断）
    try:
        flags = ida_bytes.get_full_flags(ea)
        iscode = ida_bytes.is_code(flags)
    except Exception:
        iscode = False

    if iscode:
        # 始终显示偏移（即便 off == 0）
        try:
            return f"{name}+0x{off:X}"
        except Exception:
            return name
    else:
        # 数据或变量，直接显示名称（不加 +0x0）
        return name

# ============================================================
# UI Hook：在每行渲染时被调用（确保调用 make_prefix）
# ============================================================
class PrefixUIHook(ida_kernwin.UI_Hooks):
    def func_line_rendering(self, widget, info):
        """
        info 是 ida_kernwin.func_render_info_t（或类似结构）
        使用 info.line_ea 以确保针对每行取到正确EA
        """
        try:
            # 优先使用 line_ea（针对行）；若不可用，回退到 at.toea()
            ea = getattr(info, "line_ea", None)
            if ea is None or ea == idaapi.BADADDR:
                # 回退
                try:
                    ea = info.at.toea()
                except Exception:
                    ea = idaapi.BADADDR

            if ea != idaapi.BADADDR and ea is not None:
                pfx = make_prefix(ea)
                if pfx:
                    # 强制覆盖前缀（覆盖 seg:off）
                    info.prefix = pfx
        except Exception:
            # 忽略所有异常以避免 Hook 导致 IDA 崩溃
            pass
        return 0

# ============================================================
# Debug Hook：调试时刷新视图
# ============================================================
class DebugHook(ida_dbg.DBG_Hooks):
    def _refresh(self):
        try:
            ida_kernwin.refresh_idaview_anyway()
        except Exception:
            try:
                ida_kernwin.refresh_idaview()
            except Exception:
                pass

    def dbg_ev_step(self, *args):
        self._refresh()

    def dbg_ev_bpt(self, *args):
        self._refresh()

    def dbg_ev_run_to(self, *args):
        self._refresh()

    def dbg_ev_suspend(self, *args):
        self._refresh()

# ============================================================
# 全局 hook 实例（便于卸载）
# ============================================================
prefix_hook = None
debug_hook = None

def install_hooks():
    global prefix_hook, debug_hook
    if prefix_hook is None:
        prefix_hook = PrefixUIHook()
        prefix_hook.hook()
        print("[prefix] UI hook installed")
    else:
        print("[prefix] UI hook already installed")

    if debug_hook is None:
        debug_hook = DebugHook()
        debug_hook.hook()
        print("[prefix] Debug hook installed")
    else:
        print("[prefix] Debug hook already installed")

def uninstall_hooks():
    global prefix_hook, debug_hook
    try:
        if prefix_hook is not None:
            prefix_hook.unhook()
            prefix_hook = None
            print("[prefix] UI hook uninstalled")
    except Exception:
        pass
    try:
        if debug_hook is not None:
            debug_hook.unhook()
            debug_hook = None
            print("[prefix] Debug hook uninstalled")
    except Exception:
        pass
    try:
        ida_kernwin.refresh_idaview()
    except Exception:
        pass

# ============================================================
# 初始化主入口
# ============================================================
def install():
    # 1. 加载并安装符号（如果文件存在）
    if SYMBOL_FILE:
        syms = load_symbols(SYMBOL_FILE)
        if syms:
            install_all_symbols(syms)
    # 2. 安装 hooks
    install_hooks()
    # 3. 刷新视图
    try:
        ida_kernwin.refresh_idaview()
    except Exception:
        pass
    print("[prefix] READY (IDA 9.x)")

# 如果作为脚本直接运行，执行 install()
if __name__ == "__main__":
    install()